### ISSUE TITLE
Compatibility with integration

### ISSUE THREAD

**Issue by aoumess** [quon-titative-biology/scBFA#4]
Hi ! I was just posting an information request (sorry if this is not the good place to do so) regarding the compatibility of scBFA preprocessing with multiple samples integration.
Starting with counts, I wondered how scbfa would be compatible with data integration of multiple samples ? I performed some very early tests, and while results are good (sample effect doesn't appear  too early, let's say after around 10 scbfa components), it's still present. And while, on a single sample, scbfa usually delivers the best results compared to SCT normalization + any reduction method, it does not perform so well when integrating. I know it is because of the particularity of this method, using gene activation rather than expression level, but I wondered if you had suggestions to deal with integration.
I tried to account for it using regression, either by regressing according to the samples population (in cells) rank, or by value (the amount of cells in each cluster) to give more weight to more populated clusters, but it did not mitigate the effect.
Thanks for your great work, and for any suggestion ;)

**Comment by gquon** [comment]
Have you tried regressing out the sample from which each cell was sequenced?

**Comment by aoumess** [comment]
Sorry I wasn't very clear in my first post. Yes, I tried to regress it out by two different approaches :+1: 1) by adding as regression vector the rank of the population of each sample (ie, if sample1 has 100 cells, sample2 200 and sample3 300, each cell from sample1 is attributed a regression weight of 1, from sample2 2, from sample3 3 (etc).
2) By adding as regression vector the size of the population of each sample (100 for sample1, 200 for sample2, etc).
I know it does imply that "bigger" samples have more weight than "smaller" ones, but that's the only approaches I could think of. Is there another possibility to just tell scBFA that each cell comes from the different samples (like a factor rather than a vector of ints) ? Thanks !

**Comment by gquon** [comment]
If you have M samples, then make (M-1) vectors, where for. vector m, the entries of the vector are all 0 except for those samples that came from sample m - those should be 1. Your Mth sample will be encoded by a vector of all zeros already, so you only need M-1 vectors. This is what's known as a "one-hot encoding" of the samples.

**Comment by aoumess** [comment]
Hey ! Never thought about using a contrast matrix, stupid me ! Thanks for the tip, I tried it and it increased the results quality. There are still remains of sample effect, but in much more far components, and probably due to a single sample that has more than 5x more cells than the 5 other samples.
Thanks again for your help ;)
